
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prkfkiwgmrwnwwxvkgdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBya2ZraXdnbXJ3bnd3eHZrZ2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjcwMDcsImV4cCI6MjA2MDc0MzAwN30._HBKVnm9eg0yL3XfVNWT7jiOEj6tmJYuYBgbw5RRQAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    fetch: (url: string, options: RequestInit) => {
      // Add custom fetch behavior for better error handling
      return fetch(url, options).catch(error => {
        console.error("Network error during Supabase request:", error);
        throw error;
      });
    }
  }
});

// Helper function to check if a student ID is a local temporary ID
export const isLocalStudentId = (studentId: string): boolean => {
  return studentId.includes('temp-id') || !studentId.match(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
};
